[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "ERC721A-Upgradeable/=lib/ERC721A-Upgradeable/",
]

# File system permissions
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./broadcast" },
    { access = "read", path = "./out" }
]


[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://localhost:8545"

# Etherscan API keys for verification
[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }