[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "ERC721A/=lib/ERC721A/",
]
